server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
  config: classpath:logback-spring.xml

practice:
  log:
    file-name: practice
    file-path: log/
    error-file-name: practice_error
    error-file-path: log/practice
    max-history: 30

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/practice?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: admin

  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        pysical-starategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      enabled: true
      probes:
        enabled: true